# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
pod 'Firebase/AdMob'
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Messaging'
pod 'Firebase/RemoteConfig'
pod 'Firebase/Storage'
pod 'Firebase/Crashlytics'
pod 'GoogleSignIn'

target 'medication-tracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for medication-tracker

  target 'medication-trackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'medication-trackerUITests' do
    # Pods for testing
  end

end
